name: Continuous Deployment - ECS Deploy

on:
  push:
    branches: [ "main" ]
  workflow_run:
    workflows: ["Continuous Integration - Build & Push"]
    types:
      - completed

env:
  AWS_REGION: us-east-1
  ECS_CLUSTER: shopsmart-cluster
  ECS_SERVICE_BACKEND: shopsmart-backend-service
  ECS_SERVICE_FRONTEND: shopsmart-frontend-service
  CONTAINER_NAME_BACKEND: backend
  CONTAINER_NAME_FRONTEND: frontend

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      # --- BACKEND DEPLOY ---
      - name: Fill in the new image ID in the Backend task definition
        id: task-def-backend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/backend-task-def.json
          container-name: ${{ env.CONTAINER_NAME_BACKEND }}
          image: ${{ steps.login-ecr.outputs.registry }}/shopsmart-backend:${{ github.sha }}

      - name: Deploy Backend to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-backend.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_BACKEND }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true

      # --- FRONTEND DEPLOY ---
      - name: Fill in the new image ID in the Frontend task definition
        id: task-def-frontend
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: .aws/frontend-task-def.json
          container-name: ${{ env.CONTAINER_NAME_FRONTEND }}
          image: ${{ steps.login-ecr.outputs.registry }}/shopsmart-frontend:${{ github.sha }}

      - name: Deploy Frontend to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def-frontend.outputs.task-definition }}
          service: ${{ env.ECS_SERVICE_FRONTEND }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
